In [1]:
import sys
sys.path.append('../../Scripts')
from PostProcessingScripts import * 
import pandas as pd 
import string 
# just to make the cells appear wider:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))


import h5py as h5
import numpy as np
import os
import matplotlib.pyplot as plt
import pandas as pd
import string


import ClassFormationChannels as FC 

In [2]:
# to obtain properties of ALL binaries simulated, do this:

DCOtype = 'BHNS'   # You can change this line to 'BBH', 'BHNS' 'BNS', or 'ALL' (All DCOs)  # change this line! 


# add path to where the COMPASOutput.h5 file is stored. 
# For you the part '/Volumes/Andromeda/DATA/AllDCO_bugfix/fiducial/' is probably different
path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_25/COMPASCompactOutput_'+ DCOtype +'_B.h5' # change this line! 
fdata_B = h5.File(path)
# shows the different files within the hdf5 folder 
print(fdata_B.keys())



# add path to where the COMPASOutput.h5 file is stored. 
# For you the part '/Volumes/Andromeda/DATA/AllDCO_bugfix/fiducial/' is probably different
path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_5/COMPASCompactOutput_'+ DCOtype +'_C.h5' # change this line! 
fdata_C = h5.File(path)

# add path to where the COMPASOutput.h5 file is stored. 
# For you the part '/Volumes/Andromeda/DATA/AllDCO_bugfix/fiducial/' is probably different
path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_75/COMPASCompactOutput_'+ DCOtype +'_D.h5' # change this line! 
fdata_D = h5.File(path)





[u'RLOF', u'commonEnvelopes', u'doubleCompactObjects', u'formationChannels', u'supernovae', u'systems', u'weights_detected', u'weights_detectedPerRedshift', u'weights_intrinsic', u'weights_intrinsicPerRedshift']


In [3]:
print(fdata_B['doubleCompactObjects'].keys())
print()
print(fdata_B['formationChannels'].keys())

[u'COCoreMassDCOFormation1', u'COCoreMassDCOFormation2', u'ECSNPrimary', u'ECSNSecondary', u'HeCoreMassDCOFormation1', u'HeCoreMassDCOFormation2', u'ID', u'M1', u'M1ZAMS', u'M2', u'M2ZAMS', u'Metallicity1', u'Metallicity2', u'PISNPrimary', u'PISNSecondary', u'PPISNPrimary', u'PPISNSecondary', u'PrimaryMTCase', u'RL1to2PostCEE', u'RL1to2PreCEE', u'RL2to1PostCEE', u'RL2to1PreCEE', u'RLOFSecondaryAfterCEE', u'SecondaryMTCase', u'SemiMajorAxisPostCEE', u'SemiMajorAxisPreCEE', u'USSNPrimary', u'USSNSecondary', u'coreMassDCOFormation1', u'coreMassDCOFormation2', u'doubleCommonEnvelopeFlag', u'drawnKick1', u'drawnKick2', u'eccentricityDCOFormation', u'eccentricityInitial', u'eccentricityPrior2ndSN', u'kickDirectionPower', u'mergesInHubbleTimeFlag', u'optimisticCEFlag', u'phiSupernova1', u'phiSupernova2', u'recycledPrimary', u'recycledSecondary', u'relativeVelocity2ndSN', u'samplingPhase', u'seed', u'separationDCOFormation', u'separationInitial', u'separationPrior2ndSN', u'sigmaKickBH', u'sigm

In [4]:
BHNS_seeds_B = fdata_B['doubleCompactObjects']['seed'][...].squeeze()

print(BHNS_seeds_B)
system_seeds_B = fdata_B['systems']['SEED'][...].squeeze()
FC_seed_B = fdata_B['formationChannels']['m_randomSeed'][...].squeeze()

mask = np.in1d(FC_seed_B, BHNS_seeds_B)


[   5005630    5027727   45007041 ... 5170000141 5185001269 5185002492]


In [21]:
Seed = 40001314

mask = fdata_B['doubleCompactObjects']['seed'][...].squeeze() == 40001314
M1 = BHNS_seeds_B = fdata_B['doubleCompactObjects']['M1'][...].squeeze()[mask]
Metallicity1 = BHNS_seeds_B = fdata_B['doubleCompactObjects']['Metallicity1'][...].squeeze()[mask]
print(M1)
print(Metallicity1)

[14.7185]
[0.0001]


In [5]:
print(fdata_B['formationChannels'])


path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_25/COMPASCompactOutput_'+ DCOtype +'_B.h5' # change this line! 
fc = FC.FormationChannels(path = path,verbose=True)
fc.formationChannelsSeeds(seeds=FC_seed_B)



<HDF5 group "/formationChannels" (36 members)>
self.booleanFilter 
 Looking up the seeds/systems and creating mask for formation Channels. 
Doing the formation channels for 738537 systems
self.header 
 Sorted which columns from formation channels we use
Counting/sorting the unique Channels
self.sortedChannels self.sortedCounts 
 Combining the counts and channels in arrays
(15581.352363435699, 'sum sorted counts')
Done
self.rankArray 
 Creating column with rank of each system, patience required :)
Done :D 
self.sortedSeeds 
 Creating array per channel with all seeds of that channel
self.sortedStrings 
 Constructing human readable string for each of the unique Channels (Magic) 
 :D :D 
 finished in total we have 108 channels for 15581.352363435699 systems


In [19]:
for ii in range(3):
    
    print(fc.sortedStrings)[ii]
    print(fc.sortedSeeds[ii][0])
#     print(len(fc.sortedSeeds[ii]))
    print()
    
    print('--- in D ---')
    seeds=fc.sortedSeeds[ii]
    path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_75/COMPASCompactOutput_'+ DCOtype +'_D.h5' # change this line! 
    fc_D = FC.FormationChannels(path = path,verbose=True)
    fc_D.formationChannelsSeeds(seeds=seeds)
    for ii in range(3):
        print(fc_D.sortedStrings)[ii]
#         print(fc_D.sortedSeeds[ii])
        print(len(fc_D.sortedSeeds[ii]))
        print()    

 ->mt_primary_ep1 P=HG  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=CHeB  ->CEE ->mt_secondary_ep2 P=BH  S=HeHG  ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=HeHG  -> merged within Hubble=True -> binary disrupted=False
[  40001314   40001957   55008870 ... 4885014917 4885015425 4885015839]
()
--- in D ---
self.booleanFilter 
 Looking up the seeds/systems and creating mask for formation Channels. 
Doing the formation channels for 4387 systems
self.header 
 Sorted which columns from formation channels we use
Counting/sorting the unique Channels
self.sortedChannels self.sortedCounts 
 Combining the counts and channels in arrays
(188.88257826583916, 'sum sorted counts')
Done
self.rankArray 
 Creating column with rank of each system, patience required :)
Done :D 
self.sortedSeeds 
 Creating array per channel with all seeds of that channel
self.sortedStrings 
 Constructing human readable string for each of the unique Channels (Magic) 
 :D :D 
 finish

In [14]:




path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_75/COMPASCompactOutput_'+ DCOtype +'_D.h5' # change this line! 
fc_D = FC.FormationChannels(path = path,verbose=True)
fc_D.formationChannelsSeeds(seeds=FC_seed_B)




self.booleanFilter 
 Looking up the seeds/systems and creating mask for formation Channels. 
Doing the formation channels for 9130 systems
self.header 
 Sorted which columns from formation channels we use
Counting/sorting the unique Channels
self.sortedChannels self.sortedCounts 
 Combining the counts and channels in arrays
(450.76416767514155, 'sum sorted counts')
Done
self.rankArray 
 Creating column with rank of each system, patience required :)
Done :D 
self.sortedSeeds 
 Creating array per channel with all seeds of that channel
self.sortedStrings 
 Constructing human readable string for each of the unique Channels (Magic) 
 :D :D 
 finished in total we have 43 channels for 450.76416767514155 systems


In [17]:
for ii in range(3):
    
    print(fc_D.sortedStrings)[ii]
    print(fc_D.sortedSeeds[ii])
    print(len(fc_D.sortedSeeds[ii]))
    print()

 ->mt_primary_ep1 P=EAGB  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=CHeB  ->CEE ->mt_secondary_ep2 P=BH  S=HeHG  ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=HeHG  -> merged within Hubble=True -> binary disrupted=False
[1020021498 1245027058 1215016829 ... 3790000398 3790002136 3770004898]
1165
()
 ->mt_primary_ep1 P=CHeB  S=MS  ->CEE ->ccSN primary  ->mt_secondary_ep1 P=BH  S=HG  ->mt_secondary_ep2 P=BH  S=HeHG  ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=HeHG  -> merged within Hubble=True -> binary disrupted=False
[1435021292 1465032736 1530019334 ... 4205067527 4245052518 4275005875]
1284
()
 ->mt_primary_ep1 P=CHeB  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=CHeB  ->CEE ->mt_secondary_ep2 P=BH  S=HeHG  ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=HeHG  -> merged within Hubble=True -> binary disrupted=False
[ 420005585  840023550  900003994 ... 4290012676 4250

In [41]:
# to obtain properties of ALL binaries simulated, do this:

DCOtype = 'BHNS'   # You can change this line to 'BBH', 'BHNS' 'BNS', or 'ALL' (All DCOs)  # change this line! 


# add path to where the COMPASOutput.h5 file is stored. 
# For you the part '/Volumes/Andromeda/DATA/AllDCO_bugfix/fiducial/' is probably different
path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_25/COMPASCompactOutput_'+ DCOtype +'_B.h5' # change this line! 
fdata_B = h5.File(path)
# shows the different files within the hdf5 folder 
print(fdata_B['systems'].keys())

print(fdata_B['doubleCompactObjects'].keys())






def print_sum_and_flag(keys=['systems'], DCOkeys=['M1', 'M2'], which='B'):
    # we are going to check with successfull mergers in B: 
    BHNS_seeds_B = fdata_B['doubleCompactObjects']['seed'][...].squeeze()
    metallicities = fdata_B['doubleCompactObjects']['Metallicity1'][...].squeeze()
    print()
    print('------')
    print(which)
    if which=='C':
        path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_5/COMPASCompactOutput_'+ DCOtype +'_C.h5' # change this line! 
        pathBBH = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_5/COMPASCompactOutput_'+ 'BBH' +'_C.h5' # change this line! 

    elif which=='D':
        path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_75/COMPASCompactOutput_'+ DCOtype +'_D.h5' # change this line!    
        pathBBH = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_75/COMPASCompactOutput_'+ 'BBH' +'_D.h5' # change this line!   
    elif which=='B':
        path = '/Volumes/Andromeda/DATA/AllDCO_bugfix/massTransferEfficiencyFixed_0_25/COMPASCompactOutput_'+ DCOtype +'_B.h5' # change this line!    
        
    
    fewseeds = np.asarray(BHNS_seeds_B[0:5])
    print(fewseeds)
    fdata = h5.File(path)
    mask_BHNS = np.in1d(fdata['systems']['SEED'][...].squeeze(), fewseeds) 
    
    
    
    for key in keys:
        fraction = float(np.sum(fdata['systems'][key][...].squeeze()[mask_BHNS]==1))/np.sum(mask_BHNS)
        print(key, fraction, fdata['systems'][key][...].squeeze()[mask_BHNS])
        
        
        
    mask_BHNS = np.in1d(fdata['doubleCompactObjects']['seed'][...].squeeze(), fewseeds) 
    
    
    
    for key in DCOkeys:
        fraction = np.sum(fdata['doubleCompactObjects'][key][...].squeeze()[mask_BHNS]==1)/np.sum(mask_BHNS)
        print(key, fraction, fdata['doubleCompactObjects'][key][...].squeeze()[mask_BHNS])

    if which in ['C', 'D']:
        print 'BBH:'
        fdataBBH = h5.File(pathBBH)
        mask_BBH = np.in1d(fdataBBH['doubleCompactObjects']['seed'][...].squeeze(), fewseeds) 
        fraction = np.sum(fdataBBH['doubleCompactObjects'][key][...].squeeze()[mask_BBH]==1)/np.sum(mask_BBH)
        print(key, fraction, fdataBBH['doubleCompactObjects'][key][...].squeeze()[mask_BBH])


print_sum_and_flag(keys=['disbound', 'stellar_merger'], DCOkeys=['seed', 'M1', 'M2'], which='B')
print_sum_and_flag(keys=['disbound', 'stellar_merger'], DCOkeys=['seed', 'M1', 'M2'], which='C')
print_sum_and_flag(keys=['disbound', 'stellar_merger'], DCOkeys=['seed', 'M1', 'M2'], which='D')





[u'ID', u'Metallicity1', u'Metallicity2', u'SEED', u'disbound', u'eccentricity', u'mass1', u'mass2', u'meanAnomaly1', u'meanAnomaly2', u'omega1', u'omega2', u'phi1', u'phi2', u'samplingPhase', u'separation', u'stellar_merger', u'theta1', u'theta2', u'weight']
[u'COCoreMassDCOFormation1', u'COCoreMassDCOFormation2', u'ECSNPrimary', u'ECSNSecondary', u'HeCoreMassDCOFormation1', u'HeCoreMassDCOFormation2', u'ID', u'M1', u'M1ZAMS', u'M2', u'M2ZAMS', u'Metallicity1', u'Metallicity2', u'PISNPrimary', u'PISNSecondary', u'PPISNPrimary', u'PPISNSecondary', u'PrimaryMTCase', u'RL1to2PostCEE', u'RL1to2PreCEE', u'RL2to1PostCEE', u'RL2to1PreCEE', u'RLOFSecondaryAfterCEE', u'SecondaryMTCase', u'SemiMajorAxisPostCEE', u'SemiMajorAxisPreCEE', u'USSNPrimary', u'USSNSecondary', u'coreMassDCOFormation1', u'coreMassDCOFormation2', u'doubleCommonEnvelopeFlag', u'drawnKick1', u'drawnKick2', u'eccentricityDCOFormation', u'eccentricityInitial', u'eccentricityPrior2ndSN', u'kickDirectionPower', u'mergesInHubbl

/Users/floorbroekgaarden/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:63: RuntimeWarning: divide by zero encountered in long_scalars
